name: ArrowArc Build

on:
  push:
    branches:
      - main
    paths:
      - '**.go'           # Only trigger on changes to Go files
      - go.mod            # Trigger on changes to go.mod
      - go.sum            # Trigger on changes to go.sum
      - 'pkg/**'          # Trigger on changes to anything in the pkg directory
      - 'integrations/**' # Trigger on changes to anything in the integrations directory
  pull_request:
    branches:
      - main
    paths:
      - '**.go'           # Only trigger on changes to Go files
      - go.mod            # Trigger on changes to go.mod
      - go.sum            # Trigger on changes to go.sum
      - 'pkg/**'          # Trigger on changes to anything in the pkg directory
      - 'integrations/**' # Trigger on changes to anything in the integrations directory

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.0

    - name: Install dependencies
      run: go mod tidy

    - name: Run linters
      run: go vet ./...
 
    - name: Run tests
      run: go test ./...

    if: github.repository == 'ArrowArc/ArrowArc'
