name: ArrowArc Build

on:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - go.mod
      - go.sum
      - 'pkg/**'
      - 'integrations/**'
    # types: [push]
  pull_request:
    branches:
      - main
    paths:
      - '**.go'
      - go.mod
      - go.sum
      - 'pkg/**'
      - 'integrations/**'
    # Only trigger on pull requests if the base repository is ArrowArc/ArrowArc (avoids building forks)
    types: [opened, synchronize]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.0

    - name: Install dependencies
      run: go mod tidy

    - name: Run linters
      run: go vet ./...
 
    - name: Run tests
      run: go test ./...

    if: github.repository == 'ArrowArc/ArrowArc'
