name: ArrowArc Build

on:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - go.mod
      - go.sum
      - 'pkg/**'
      - 'integrations/**'
  pull_request:
    branches:
      - main
    paths:
      - '**.go'
      - go.mod
      - go.sum
      - 'pkg/**'
      - 'integrations/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.0

    - name: Install dependencies
      run: go mod tidy

    - name: Run linters
      run: go vet ./...
 
    - name: Run tests
      run: go test ./...

    # Only run the build if it's either a push event or a PR in the main repository
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.repository == 'ArrowArc/ArrowArc')
